name: 'Build SuperTux Nightly Flatpak'

on:
 push


jobs:
  grabDeps:
    runs-on: ubuntu-latest
    steps:
      - name: Grabbing dependencies
        run: |
           export DEBIAN_FRONTEND=noninteractive
           sudo apt update
           sudo apt -y install lsb-release
           lsb_release -a
           sudo apt install -y -qq clang \
           gcc \
           g++ \
           cmake \
           build-essential \
           libc++-dev \
           libogg-dev \
           libvorbis-dev \
           libopenal-dev \
           libboost-all-dev \
           libsdl2-dev \
           libsdl2-image-dev \
           libsdl2-mixer-dev \
           libjsoncpp-dev \
           libpng-dev \
           libglew-dev \
           software-properties-common \
           git
          
  build:
    needs: grabDeps
    runs-on: ubuntu-latest
    steps:
      - name: Building Flatpak
      - uses: actions/checkout@v3
      - run: |
           sudo apt update
           sudo apt install -y -qq flatpak flatpak-builder
           sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
           pwd
           ls
           tree .
           flatpak-builder --repo=supertux-repo/ supertux-build/ org.supertuxproject.SuperTux_Nightly.json
           flatpak build-bundle supertux-repo/ supertux-nightly.flatpak org.supertuxproject.SuperTux_Nightly